# Generated by Django 4.1.7 on 2023-02-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('linked_in_profile', models.CharField(max_length=100)),
                ('github_profile', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=1000)),
                ('twitter_profile', models.CharField(max_length=50)),
            ],
        ),
    ]
